import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '../styles/main.module.scss';
import Header from '@/components/common/Header';
import RightBox from '@/components/RightBox';
import MapSection from '@/components/home/MapSection';
import { Store } from '../types/store';
import { useActions, useValues } from '@/context/procider';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  // Store;
  stores: Store[];
}

export default function Home({ stores }: Props) {
  const { setStores } = useActions();

  useEffect(() => {
    setStores(stores);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <>
        <Header RightElements={<RightBox />} />
        <main className={styles.main} style={{}}>
          <MapSection />
        </main>
      </>
    </>
  );
}

export async function getStaticProps() {
  const stores = await (await import('../public/stores.json')).default;

  return {
    props: { stores },
    revalidate: 60 * 60,
  };
}
